# site.yml
---
- hosts: pxe
  become: true
  roles:
    - bertvv.rh-base
    - bertvv.dhcp
    - bertvv.tftp
    - bertvv.pxeserver

- hosts: udpcast
  become: true
  roles:
    - bertvv.rh-base
    - udpcast

